directories:
  output: build
  buildResources: build
extraFiles: []
publish:
  - provider: generic
    url: https://ostrichalgorithm.github.io/hasaki/
productName: hasaki
appId: org.ostrichalgorithm.hasaki
files:
  - filter:
      - dist/electron/**/*
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
win:
  icon: build/icons/icon.ico
  target: nsis
linux:
  target: deb
  icon: build/icons
electronVersion: 13.5.2
